//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSSGroup.Datacap.CustomActions.FormulaProcessor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSSGroup.Datacap.CustomActions.FormulaProcessor.Resources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string Delimiter {
            get {
                return ResourceManager.GetString("Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt;&lt;!=&amp;&amp;|!^/*-+.
        /// </summary>
        internal static string Operators {
            get {
                return ResourceManager.GetString("Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [/[\]\^\$\|\*\+\!&amp;\-+=&lt;&gt;:;, ]{1,}.
        /// </summary>
        internal static string RegexFormulaMatch {
            get {
                return ResourceManager.GetString("RegexFormulaMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([a-zA-Z_][a-zA-Z0-9_]*)\((?:[^()]*|(?&lt;open&gt; \( )|(?&lt;-open&gt; \) ))+(?(open)(?!))\)&quot;.
        /// </summary>
        public static string RegexParentMatch {
            get {
                return ResourceManager.GetString("RegexParentMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ().
        /// </summary>
        internal static string Separators {
            get {
                return ResourceManager.GetString("Separators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
    }
}
