//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convertion.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorAr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorAr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Convertion.Properties.ErrorAr", typeof(ErrorAr).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! The number of arguments Exponentiation!!!.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Overflow in Exponentiation !!!.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! The number of arguments Division!!!.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Div by zero in Division !!!.
        /// </summary>
        internal static string _21 {
            get {
                return ResourceManager.GetString("_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! The number of arguments Multiplication!!!.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Overflow in Multiplication !!!&quot;.
        /// </summary>
        internal static string _31 {
            get {
                return ResourceManager.GetString("_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! The number of arguments Subtraction!!!.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Overflow in  Subtraction!!!.
        /// </summary>
        internal static string _41 {
            get {
                return ResourceManager.GetString("_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! The number of arguments Addition!!!.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Overflow in Addition !!!.
        /// </summary>
        internal static string _51 {
            get {
                return ResourceManager.GetString("_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Function is not defined !!!.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Unknown function !!!.
        /// </summary>
        internal static string _66 {
            get {
                return ResourceManager.GetString("_66", resourceCulture);
            }
        }
    }
}
