//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datacap.Math.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datacap.Math.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is string from default local for the .NET actions.
        /// </summary>
        internal static string SampleStringNET {
            get {
                return ResourceManager.GetString("SampleStringNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;rrx namespace=&quot;DatacapMath&quot; v=&quot;9.0.1.2.2&quot;&gt;
        ///&lt;!-- === .NET Action Definition and Help === --&gt;
        ///&lt;!-- Licensed Materials - Property of IBM
        ///
        /// 5725-C15
        /// © Copyright IBM Corp. 1994, 2014 All Rights Reserved
        /// US Government Users Restricted Rights - Use, duplication or
        /// disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
        /// --&gt;
        ///
        ///&lt;!-- format: &lt;net ref=&quot;C#Namespace.Class&quot;&gt; --&gt;
        ///&lt;net ref=&quot;Datacap.Math.Actions&quot;&gt;
        ///  &lt;!-- Actions and Properties defined here are displayed in alphabetic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TheRRX {
            get {
                return ResourceManager.GetString("TheRRX", resourceCulture);
            }
        }
    }
}
